spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    username: root
    password: Greenism@2017

logging:
  level:
    com:
      zaxxer:
        hikari: error
